### ISSUE TITLE
Method not found "ShowStatus"

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/Commander-MarkdownMonster-Addin#2]
## Description
Trying to run any command gives the following error:

>Method not found: Void MarkdownMonster.MainWindow.ShowStatus(System.String, Int32)'.

## Environment
* Windows 10 x64
* MM version v1.10.5.0
* Commander version 0.4

## More Information
Even creating and running a new command with just `string x = "";` fails. This is my first time trying the addin, so I don't know if it was working before.

I was hoping to use this addin to automate creating blog posts locally. Full C# scripting is pretty sweet!

Here's the log:

```txt
4/14/2018 3:31:47 PM - Last Resort Handler
Markdown Monster v1.10.5.0
10.0.16299.15.x86fre.rs3_release.170928-1534 - en-US - NET 4.7.1 - 32 bit
en-US - en-US    
---
CommanderAddin
   at CommanderAddin.CommanderAddin.RunCommand(CommanderCommand command)
   at CommanderAddin.CommanderWindow.ToolButtonRunCommand_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------
```

**Comment by RickStrahl** [comment]
Can you try and update mm and the addin to latest version? There was a binary compatibility change in a recent version. It should work for the latest release with the last addin.

**Comment by bladewolf55** [comment]
If you mean the latest released versions, I had already checked that and am
running them.

MM    v1.10.5
Addin v0.4

Do you want me to do a complete uninstall/reinstall (preserving my
settings, though)?




--
Charles L Flatt
513-535-0764 (m)

"You can't go around changing your definition of right and wrong (or smart
and stupid) just because doing the wrong thing happens to be really
convenient." --Harry Dresden, Cold Days

**Comment by RickStrahl** [comment]
Double checked and could duplicate. A little odd as I updated the addin, but it looks like the last update I pushed actually pushed an older version.

Give it another try with v0.4.1... should work now.

Thanks for the heads up.

**Comment by bladewolf55** [comment]
It was just dumb luck that I tried the addin; someone else would have
noticed before too long.

I uninstalled/installed the addin, and it's working now. Thank you!

This does lead to a feature suggestion, though, which I can formally submit
if you want. The Addin Manager doesn't seem to have an Update facility.
Here's a screenshot of mine *before* reinstalling the addin. Or have I
missed something?


I think modeling after the Visual Studio NuGet interface would do nicely.
That way, I would have known A) What my current addin version was, and B)
that I needed to update.

Thanks, again. I have some ideas for MM itself that I want to work on
through my fork, but I've been busy with...life. :-)




--
Charles L Flatt
513-535-0764 (m)

"You can't go around changing your definition of right and wrong (or smart
and stupid) just because doing the wrong thing happens to be really
convenient." --Harry Dresden, Cold Days

**Comment by RickStrahl** [comment]
You should see updates in the addin-manager:

![image](https://user-images.githubusercontent.com/1374013/38782867-d8d3940e-4095-11e8-8aa0-b2b7521c7ec7.png)


All installed addins show at the top of the list so you should see that. This should work in current downloadable versions although I've made a few display related fixes in the last couple of days.

**Comment by bladewolf55** [comment]
The update button want there, but  I will look for it in the future. Thank
you!

**Comment by bladewolf55** [comment]
This morning I uninstalled MM, and installed the latest version (1.10.6).
Opened Addin Manager and...yay! Update buttons! I had checked beforehand,
and the button for Snippets definitely wasn't there. So all seems good, now.

Here's a short blog post I did on using the Command addin.

http://www.softwaremeadows.com/posts/create_blog_post_using_markdown_monster_command_addin/





--
Charles L Flatt
513-535-0764 (m)

"You can't go around changing your definition of right and wrong (or smart
and stupid) just because doing the wrong thing happens to be really
convenient." --Harry Dresden, Cold Days

**Comment by RickStrahl** [comment]
Ah nice - cool use of the Commander addin :-) It's not easy to create
longer scripts with that because well you can't easily debug that code -
you just have to Console.WriteLine() debugging which is a bit of a pain.

Two things:

You can create a full addin (it's actually quite easy) at which point you
have a real C# project which makes it a bit easier to discover
functionality (gotta love Intellisense) and lets you debug into the code.

Most of the features you're using are actually in the New WebLog Post
dialog - it'll create the title, front matter and set up your post in a
folder structure. I like the idea of opening the folder browser in that
location as well.

+++ Rick ---




--

+++ Rick ---

Rick Strahl
West Wind Technologies
Making Waves on the Web

weblog.west-wind.com
markdownmonster.west-wind.com

**Comment by bladewolf55** [comment]
Thanks, Rick. An addin's on my radar, but this was reasonably quick. (In
fact, it was less quick than if I'd written a crappy Windows Form app, but
it gave me a chance to learn more about MM's features and limitations.)


--
Charles L Flatt
513-535-0764 (m)

"You can't go around changing your definition of right and wrong (or smart
and stupid) just because doing the wrong thing happens to be really
convenient." --Harry Dresden, Cold Days
